Repository AY2122S2-CS2103T-W14-1/tp, pull requests merged in 2022-04, with the labels that each got.

#146 Add implementation details and update UML diagrams for DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/BorrowCommandActivityDiagram.puml
  docs/diagrams/BorrowCommandSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelImplementation.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/RequestBookCommandActivityDiagram.puml
  docs/diagrams/RequestBookCommandSequenceDiagram.puml
  docs/diagrams/ReturnAllBooksCommandActivityDiagram.puml
  docs/diagrams/ReturnAllBooksCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/BorrowCommandActivityDiagram.png
  docs/images/BorrowCommandSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelImplementation.png
  docs/images/RequestBookCommandActivityDiagram.png
  docs/images/RequestBookCommandSequenceDiagram.png
  docs/images/ReturnAllBooksCommandActivityDiagram.png
  docs/images/ReturnAllBooksCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ReturnAllBooksCommand.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/patron/PatronCommandParser.java
Labels: documentation

#148 UG patron format changes
  docs/UserGuide.md
  docs/images/patron-add-1.png
  docs/images/patron-add-2.png
  docs/images/patron-delete-1.png
  docs/images/patron-delete-2.png
  docs/images/patron-edit-1.png
  docs/images/patron-edit-2.png
  docs/images/patron-edit-3.png
  docs/images/patron-edit-4.png
  docs/images/patron-find-1.png
  docs/images/patron-find-2.png
  docs/images/patron-list-1.png
  docs/images/patron-list-2.png
  docs/images/patron-overdue-1.png
  docs/images/patron-overdue-2.png
Labels: documentation, priority.High

#149 Add Isbn checksum section for User Guide
  docs/UserGuide.md
Labels: documentation

#200 Branch v1.4 bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/commands/book/DeleteBookCommand.java
  src/main/java/seedu/address/logic/commands/book/EditBookCommand.java
  src/main/java/seedu/address/logic/commands/book/RelatedBookCommand.java
  src/main/java/seedu/address/logic/commands/book/RequestBookCommand.java
  src/main/java/seedu/address/logic/commands/patron/DeletePatronCommand.java
  src/main/java/seedu/address/logic/commands/patron/EditPatronCommand.java
Labels: type.Bug

#201 Branch date bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/book/RequestBookCommand.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/model/LibTask.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/BookList.java
  src/main/java/seedu/address/model/book/BookStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/book/RequestBookCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/AddPatronCommandTest.java
  src/test/java/seedu/address/model/LibTaskTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/book/BookListTest.java
Labels: type.Bug

#205 Bug fixes for PreviousCommand
  src/main/java/seedu/address/logic/commands/PreviousCommand.java
  src/main/java/seedu/address/logic/parser/LibTaskParser.java
  src/test/java/seedu/address/logic/commands/PreviousCommandTest.java
Labels: type.Bug

#204 PE Dry Run Bug Report fixes.
  src/main/java/seedu/address/model/patron/Email.java
  src/main/java/seedu/address/model/patron/Id.java
  src/test/java/seedu/address/model/patron/IdTest.java
Labels: type.Bug, priority.High, bug.Functionality

#207 Fix ped bugs
  docs/UserGuide.md
Labels: bug.Documentation

#211 Branch UG DG Additions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/OverduePatronCommandActivityDiagram.puml
  docs/diagrams/OverduePatronCommandSequenceDiagram.puml
  docs/images/OverduePatronCommandActivityDiagram.png
  docs/images/OverduePatronCommandSequenceDiagram.png
Labels: documentation, priority.High

#209 Update DG for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/RelatedBookCommandActivityDiagram.puml
  docs/diagrams/RelatedBookCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/LabeledGUI.png
  docs/images/RelatedBookCommandActivityDiagram.png
  docs/images/RelatedBookCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/book/RelatedBookCommand.java
Labels: documentation

#214 UGDG
  docs/DeveloperGuide.md
  docs/diagrams/FindBookCommandActivityDiagram.puml
  docs/diagrams/FindBookCommandSequnceDiagram.puml
  docs/images/FindBookCommandActivityDiagram.png
  docs/images/FindBookCommandSequenceDiagram.png
Labels: documentation

#216 Update headers in DG
  docs/DeveloperGuide.md
Labels: documentation

#218 UG DG additions
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#220 Branch final UGDG changes
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#225 Format UG to page break nicely
  docs/UserGuide.md
  docs/images/patron-edit-11.png
  docs/images/patron-edit-21.PNG
  docs/images/patron-edit-31.PNG
  docs/images/patron-edit-41.PNG
  docs/images/patron-find-2.png
  docs/images/patron-overdue-21.PNG
Labels: documentation, priority.Medium

#224 Add line spacing and line breaks to improve the DG for pdf conversion
  docs/DeveloperGuide.md
Labels: documentation

#228 Update UI and UI labeled diagrams in UG
  docs/UserGuide.md
  docs/images/LabeledGUI.png
  docs/images/Ui.png
Labels: documentation

#229 Update PPP and About Us
  docs/AboutUs.md
  docs/team/yuqitanyq.md
Labels: documentation, priority.High

#230 Branch final ug dg
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#235 Changes to Grammer in DG
  docs/DeveloperGuide.md
Labels: documentation

#232 DG manual testing and UG command bold bug.
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, documentation, priority.High, bug.Documentation

#237 Refine User Guide
  docs/UserGuide.md
Labels: documentation, priority.High

#239 Edit DG to ensure better understanding of features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindBookCommandSequnceDiagram.puml
  docs/images/FindBookCommandActivityDiagram.png
  docs/images/FindBookCommandSequenceDiagram.png
Labels: documentation

#240 Update UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ReferenceFrameBookRelatedSequenceDiagram.puml
  docs/diagrams/RelatedBookCommandSequenceDiagram.puml
  docs/images/ReferenceFrameBookRelatedSequenceDiagram.png
  docs/images/RelatedBookCommandSequenceDiagram.png
  docs/images/Ui.png
  docs/team/yl-ang.md
Labels: documentation

#242 Glossary updates, removed italics and weblinks on glossary keywords.
  docs/DeveloperGuide.md
Labels: documentation, priority.High, bug.Documentation

#244 Glossary updates, removed italics and weblinks on glossary keywords.
  docs/UserGuide.md
Labels: documentation, priority.High, bug.Documentation

#246 Fix User Guide for Book Edit Command
  docs/UserGuide.md
Labels: documentation, priority.High, bug.Documentation

#247 Finalize DG diagrams and reduce manual testing section
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelImplementation.puml
  docs/diagrams/RequestBookCommandActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram2.png
  docs/images/ModelClassDiagram3.png
  docs/images/ModelImplementation.png
  docs/images/ParserClasses.png
  docs/images/RequestBookCommandActivityDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.High

#249 Refine UG for v1.4b
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/patron-edit-11.png
  docs/images/patron-edit-21.PNG
  docs/images/patron-edit-31.PNG
  docs/images/patron-edit-41.PNG
Labels: documentation

#251 Update Bing Sen's PPP
  docs/team/bingsen0806.md
Labels: documentation

#252 Fix bug where valid dates are not accepted for borrow command
  src/main/java/seedu/address/model/book/BookStatus.java
Labels: bug.Functionality

#255 Change numbering for extensions in Use cases
  docs/DeveloperGuide.md
Labels: documentation

#256 PPP and Patron name bug.
  docs/team/aditi2313.md
  src/main/java/seedu/address/model/patron/Name.java
Labels: documentation, priority.High

#258 Branch ppp
  docs/team/aditi2313.md
Labels: documentation, priority.High, bug.Documentation

#259 PPP and Patron name bug.
  docs/team/aditi2313.md
Labels: documentation, priority.High, bug.Documentation

#260 Update the PPP
  docs/team/halpfrog.md
Labels: documentation

#261 Fix typos and correct command details under tutorial and features part
  docs/UserGuide.md
Labels: documentation

#264 Update tutorial examples
  docs/UserGuide.md
Labels: documentation

#266 Final Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram2.png
Labels: documentation, priority.High

#268 Fix typo in common classes section of DG
  docs/DeveloperGuide.md
Labels: documentation

#269 Fix minor bug in launching section of DG
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium
