Repository AY2122S2-CS2103T-W14-1/tp, pull requests merged in 2022-03, with the labels that each got.

#24 Update AboutUs for Sarthak. Add a png image for Sarthak and update PPP
  docs/AboutUs.md
  docs/images/halpfrog.png
  docs/team/halpfrog.md
Labels: documentation

#23 AboutUs and PPP updates.
  docs/AboutUs.md
  docs/images/aditi2313.png
  docs/team/aditi2313.md
Labels: documentation

#16 Update User Guide for Introduction and Quick start
  docs/UserGuide.md
Labels: documentation

#14 Update README
  README.md
  docs/images/Ui.png
Labels: documentation

#26 Add User Guide For Books Feature
  docs/UserGuide.md
Labels: documentation

#19 Add User Stories into Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#18 Add Details Of User Guide (FAQ and Command Summary)
  docs/UserGuide.md
Labels: documentation

#17 Update AboutUs and PPP
  docs/AboutUs.md
  docs/images/yuqitanyq.png
  docs/team/johndoe.md
  docs/team/yuqitanyq.md
Labels: documentation

#28 Book and Patron Feature additions to User guide
  docs/UserGuide.md
Labels: documentation

#29 Update README to include user and developer guide hyperlinks
  README.md
Labels: documentation

#30 Add Use cases, NFR and Glossary to Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#32 Update DG product scope
  docs/DeveloperGuide.md
Labels: documentation

#38 Fix layout of PPP and edit responsibilities
  docs/AboutUs.md
  docs/team/yuqitanyq.md
Labels: bug, documentation, priority.High

#37 Attempt to fix rendering bug and change the format of commands
  docs/UserGuide.md
Labels: bug, documentation, priority.High

#39 Fix rendering bug and include emojis
  docs/UserGuide.md
Labels: bug, documentation, priority.High

#40 Update index.html and config.yml to display LibTask information in index.html instead of ab3
  docs/_config.yml
  docs/index.md
Labels: documentation

#48 Add book package to include functionalities and objects representing books
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/book/Author.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/BookList.java
  src/main/java/seedu/address/model/book/BookName.java
  src/main/java/seedu/address/model/book/Isbn.java
  src/main/java/seedu/address/model/book/exceptions/BookNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAuthor.java
  src/main/java/seedu/address/storage/JsonAdaptedBook.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/book/AuthorTest.java
  src/test/java/seedu/address/model/book/BookListTest.java
  src/test/java/seedu/address/model/book/BookNameTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/book/IsbnTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: priority.High, type.Task

#52 Adapting Storage and Model to fit Book features
  src/main/java/seedu/address/model/book/BookNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedBook.java
  src/test/data/JsonSerializableAddressBookTest/invalidBookAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalBooksAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/book/BookNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#54 Command: Made first step to refactor into packages
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/book/AddBookCommand.java
  src/main/java/seedu/address/logic/commands/book/DeleteBookCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/book/AddBookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/DeleteBookCommandParser.java
Labels: priority.High, type.Task

#62 Branch add delete book
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/book/AddBookCommand.java
  src/main/java/seedu/address/logic/commands/book/DeleteBookCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/book/AddBookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/DeleteBookCommandParser.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBook.java
  src/test/data/JsonSerializableAddressBookTest/invalidBookAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/lengthyBooksAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalBooksAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/book/DeleteBookCommandTest.java
  src/test/java/seedu/address/logic/parser/book/AddBookCommandParserTest.java
  src/test/java/seedu/address/logic/parser/book/DeleteBookCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Story

#65 Branch edit book command
  src/main/java/seedu/address/logic/commands/book/EditBookCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/EditBookCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/book/EditBookCommandTest.java
  src/test/java/seedu/address/model/book/EditBookDescriptorTest.java
  src/test/java/seedu/address/testutil/EditBookDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#63 Adapt GUI to render patron card details
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/BookCard.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatronCard.java
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatronListCard.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, type.Task

#69 Branch list book command
  src/main/java/seedu/address/logic/commands/book/ListBookCommand.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/test/java/seedu/address/logic/commands/book/EditBookCommandTest.java
  src/test/java/seedu/address/logic/commands/book/EditBookDescriptorTest.java
  src/test/java/seedu/address/logic/commands/book/ListBookCommandTest.java
Labels: priority.High, type.Task

#70 Branch final patron refactorings and tests
  src/main/java/seedu/address/model/patron/Patron.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPatronAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPatronAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePatronAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidBookAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPatronAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/lengthyBooksAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalBooksAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPatronsAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/patron/IdTest.java
  src/test/java/seedu/address/model/patron/PatronTest.java
  src/test/java/seedu/address/model/patron/UniquePatronListTest.java
Labels: priority.High, type.Task

#66 Allow for traversal of previous commands with "u"
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/PreviousCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/PreviousCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#75 Update DG to reflect libTask
  docs/DeveloperGuide.md
Labels: documentation

#78 Branch add book status
  src/main/java/seedu/address/logic/commands/book/EditBookCommand.java
  src/main/java/seedu/address/logic/parser/book/AddBookCommandParser.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/BookStatus.java
  src/main/java/seedu/address/model/book/BookStatusType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBook.java
  src/main/java/seedu/address/storage/JsonAdaptedBookStatus.java
  src/test/data/JsonSerializableLibTaskTest/invalidBookLibTask.json
  src/test/data/JsonSerializableLibTaskTest/lengthyBooksLibTask.json
  src/test/data/JsonSerializableLibTaskTest/typicalBooksLibTask.json
  src/test/data/JsonSerializableLibTaskTest/typicalPatronsLibTask.json
  src/test/java/seedu/address/model/book/BookStatusTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: priority.Medium, type.Story

#79 Add borrow command for borrowing books
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/book/AddBookCommand.java
  src/main/java/seedu/address/logic/commands/book/DeleteBookCommand.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/logic/parser/LibTaskParser.java
  src/main/java/seedu/address/model/LibTask.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/BookList.java
  src/main/java/seedu/address/model/book/BookStatus.java
  src/test/java/seedu/address/logic/commands/BookCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/AddPatronCommandTest.java
  src/test/java/seedu/address/logic/parser/LibTaskParserTest.java
  src/test/java/seedu/address/model/book/BookListTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookStatusTest.java
Labels: priority.High, type.Story

#83 Add return command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ReturnAllBooksCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/commands/ReturnOneBookCommand.java
  src/main/java/seedu/address/logic/commands/book/DeleteBookCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LibTaskParser.java
  src/main/java/seedu/address/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/address/model/LibTask.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/BookList.java
  src/test/java/seedu/address/logic/commands/ReturnAllBooksCommandTest.java
  src/test/java/seedu/address/logic/commands/ReturnOneBookCommandTest.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/AddPatronCommandTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/LibTaskParserTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/address/model/book/BookListTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Story

#84 Adapt GUI to render book status
  src/main/java/seedu/address/ui/BookCard.java
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Task

#85 Branch small fixes
  build.gradle
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug

#87 Update README to include CodeCov badge
  README.md
Labels: documentation

#88 Add test cases and edge cases for Book and Patron
  src/test/data/JsonSerializableLibTaskTest/ManyPatronsLibTask.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/book/DeleteBookCommandParserTest.java
  src/test/java/seedu/address/logic/parser/patron/DeletePatronCommandParserTest.java
  src/test/java/seedu/address/model/book/BookNameTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/patron/IdTest.java
  src/test/java/seedu/address/model/patron/NameTest.java
  src/test/java/seedu/address/storage/JsonSerializableLibTaskTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ManyPatrons.java
Labels: type.Task

#95 Create Tests for EditBookCommandParser and Fix bugs for EditBookCommand
  src/main/java/seedu/address/logic/commands/book/EditBookCommand.java
  src/test/java/seedu/address/logic/parser/book/EditBookCommandParserTest.java
Labels: priority.High, type.Task

#96 Create RelatedBookCommandParser class
  src/main/java/seedu/address/logic/parser/book/RelatedBookCommandParser.java
Labels: priority.High, type.Story

#97 Create RelatedBookCommand class
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/book/RelatedBookCommand.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/RelatedBookCommandParser.java
  src/main/java/seedu/address/model/book/BookRelatedToPatronPredicate.java
Labels: priority.High, type.Story

#101 Create test cases for RelatedBookCommand and BookRelatedToPatronPredicate
  src/main/java/seedu/address/logic/commands/book/RelatedBookCommand.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/book/RelatedBookCommandTest.java
  src/test/java/seedu/address/model/book/BookRelatedToPatronPredicateTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
Labels: type.Task

#102 Patron overdue command
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/patron/OverduePatronCommand.java
  src/main/java/seedu/address/logic/parser/patron/PatronCommandParser.java
  src/main/java/seedu/address/model/LibTask.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/BookList.java
  src/main/java/seedu/address/model/book/BookStatus.java
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/AddPatronCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/OverduePatronCommandTest.java
Labels: priority.High, type.Story, type.Task

#108 Edited UG
  docs/UserGuide.md
Labels: documentation

#113 Update User Guide and PPP
  docs/UserGuide.md
  docs/team/yuqitanyq.md
Labels: documentation, priority.High

#116 New feature additions to User Guide.
  docs/UserGuide.md
  docs/team/yuqitanyq.md
Labels: documentation, priority.High

#111 Adapt GUI to render book requests
  build.gradle
  docs/team/yl-ang.md
  src/main/java/seedu/address/ui/BookCard.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/PatronCard.java
  src/main/java/seedu/address/ui/PatronListPanel.java
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatronListCard.fxml
Labels: type.Task

#110 Add Book find
  src/main/java/seedu/address/logic/commands/book/FindBookCommand.java
  src/main/java/seedu/address/logic/parser/book/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/book/FindBookParser.java
  src/main/java/seedu/address/model/book/BookAuthorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/book/BookNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/book/BookTagContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/book/BookAuthorContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/book/BookNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/book/BookTagContainsKeywordsPredicateTest.java
Labels: priority.Medium

#121 Add Find Book to the DG
  docs/DeveloperGuide.md
Labels: documentation

#124 Update Developer Guide And PPP
  docs/DeveloperGuide.md
  docs/team/yuqitanyq.md
Labels: documentation, priority.High

#128 Patron bug fixes
  src/main/java/seedu/address/logic/commands/patron/AddPatronCommand.java
  src/main/java/seedu/address/logic/commands/patron/DeletePatronCommand.java
  src/main/java/seedu/address/logic/commands/patron/EditPatronCommand.java
  src/main/java/seedu/address/logic/commands/patron/FindPatronCommand.java
  src/main/java/seedu/address/model/LibTask.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patron/Email.java
  src/main/java/seedu/address/model/patron/Id.java
  src/main/java/seedu/address/model/patron/Name.java
  src/main/java/seedu/address/model/patron/Patron.java
  src/main/java/seedu/address/model/patron/UniquePatronList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonLibTaskStorageTest/invalidAndValidPatronLibTask.json
  src/test/data/JsonSerializableLibTaskTest/duplicatePatronLibTask.json
  src/test/data/JsonSerializableLibTaskTest/typicalBooksLibTask.json
  src/test/data/JsonSerializableLibTaskTest/typicalPatronsLibTask.json
  src/test/java/seedu/address/logic/commands/book/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/patron/AddPatronCommandTest.java
  src/test/java/seedu/address/model/patron/PatronTest.java
  src/test/java/seedu/address/testutil/PatronBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatrons.java
Labels: type.Bug, priority.High

#134 Modify sample data in SampleDataUtil to suit mock PE user testing
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#129 Changes to UG and PPP
  docs/UserGuide.md
  docs/team/halpfrog.md
Labels: documentation

#138 Update UG introduction, about, navigation and glossary sections
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation
